version: '3.8'

services:
  api:
    build: .
    command: npm run start:dev
    volumes:
      - .:/app/
      - node_modules:/app/node_modules
    ports:
      - '3000:3000'

volumes:
  node_modules:
